version: '2'
services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - $PWD/src:/var/www/html/dqrivals
    environment:
      NGINX_SERVER_NAME: dqrivals.dev
      NGINX_DOCUMENT_ROOT: /var/www/html/dqrivals/public